# Generated by Django 5.0.6 on 2024-07-04 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("amount", models.IntegerField()),
                (
                    "wallet_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="wallet.wallet"
                    ),
                ),
            ],
        ),
    ]
