# Generated by Django 5.0.6 on 2024-07-04 14:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_alter_transaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="txid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
